// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zomlveojlqmqqovozhjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbWx2ZW9qbHFtcXFvdm96aGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTI5ODQsImV4cCI6MjA1Nzk4ODk4NH0.bDO8ekBWXMhBj1lF1yVzeSTnh8PsRTlGK33xx-2uNHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);